stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

before_script:
  - '$Env:DOTNET_CLI_UI_LANGUAGE = "en"'
  - 'dotnet --version'

build-job:       # This job runs in the build stage for .net6 projects, which runs first.
  stage: build
  #image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Building the apps..."
    - echo "Check for NuGet sources..."
    - dotnet nuget list source
    - dotnet build .\WebUI\EventingWebsite.sln -c Release
    
    - dotnet build .\ApiGateway\ApiGateway.sln -c Release

    - dotnet build .\Services\Authentication\AuthenticationService.sln -c Release
    - dotnet build .\Services\Events\EventsService.sln -c Release
    - dotnet build .\Services\Invitations\InvitationsService.sln -c Release
    - dotnet build .\Services\Subscriptions\SubscriptionsService.sln -c Release

    - echo "Build complete."

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  #image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Running unit tests... "
    - dotnet test .\WebUI\EventingWebsite.sln -c Release
    - dotnet test .\Services\Authentication\AuthenticationService.sln -c Release
    - dotnet test .\Services\Events\EventsService.sln -c Release
    - dotnet test .\Services\Invitations\InvitationsService.sln -c Release
    - dotnet test .\Services\Subscriptions\SubscriptionsService.sln -c Release
    - echo "Unit tests finished"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
