version: '3.4'

networks:
  dev:
    driver: bridge

services:
  eventingwebsite:
    container_name: EventingWebsite
    image: eventingwebsite
    build:
      context: .
      dockerfile: WebUI/WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - 5000:5000      
    depends_on:
      - postgresql
    networks:
      - dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/appuser/.microsoft/usersecrets:ro      
      - ${APPDATA}/ASP.NET/Https:/home/appuser/.aspnet/https:ro

  apigetaway:    
    container_name: ApiGetaway
    image: ocelotgateway
    build:
      context: .
      dockerfile: ApiGateway/OcelotGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - 5010:5010
    depends_on:
      - postgresql
    networks:
      - dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/appuser/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/appuser/.aspnet/https:ro

  events:    
    container_name: EventsService
    image: eventsservice
    build:
      context: .
      dockerfile: Services/Events/WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - 5020:5020
    depends_on:
      - postgresql
    networks:
      - dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/appuser/.microsoft/usersecrets:ro      
      - ${APPDATA}/ASP.NET/Https:/home/appuser/.aspnet/https:ro
    

  subscriptions:    
    container_name: SubscriptionsService
    image: subscriptionsservice
    build:
      context: .
      dockerfile: Services/Subscriptions/WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - 5030:5030
    depends_on:
      - postgresql
    networks:
      - dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/appuser/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/appuser/.aspnet/https:ro

  postgresql:
    container_name: PostgreSQL
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  db-data: